include:
  - aggregator.docker.discovery
  - aggregator.docker.tunneldigger
  - aggregator.docker.router
  - aggregator.docker.tokumx
  - aggregator.docker.postgresql
  - aggregator.docker.redis
  - aggregator.docker.nodewatcher
  - aggregator.docker.fileserver
  - aggregator.docker.builders
  - aggregator.docker.nginx
  - aggregator.docker.rocketchat
